server:
  port: 0

spring:
  application:
    name: user-service

### Eureka Configuration ###
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}:${random.value}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5