services:
  # Eureka Service Discovery
  eureka-service:
    image: ademozalp4/eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - streamix_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: on-failure

  # User Service
  user-service:
    image: ademozalp4/user-service:latest
    ports:
      - "8080"
    depends_on:
      eureka-service:
        condition: service_healthy
    networks:
      - streamix_network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/streamix_user
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      EUREKA_URI: http://eureka-service:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: on-failure

  # API Gateway Service
  apigw-service:
    image: ademozalp4/apigw-service:latest
    ports:
      - "9100:9100"
    depends_on:
      eureka-service:
        condition: service_healthy
    networks:
      - streamix_network
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_URI: http://eureka-service:8761/eureka/
      SERVER_PORT: 9100
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9100/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 50s
    restart: on-failure

networks:
  streamix_network:
    external: true