-- Insert initial privileges
INSERT INTO privileges (name, deleted, created, modified) VALUES
('USER_READ', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('USER_WRITE', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('USER_DELETE', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ROLE_READ', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ROLE_WRITE', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ROLE_DELETE', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('ADMIN_ALL', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PROFILE_READ', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PROFILE_WRITE', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CONTENT_READ', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CONTENT_WRITE', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('CONTENT_DELETE', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); 