-- Insert initial roles
INSERT INTO roles (name, deleted, created, modified) VALUES
('ADMIN', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('MODERATOR', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('USER', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP); 