name: User Service Tests

concurrency:
  group: deploy-server
  cancel-in-progress: false

on:
  push:
    branches: [ main ]
    paths:
      - 'services/user-service/**'
      - 'modules/common/**'
      - 'dependencies.gradle'
      - 'build.gradle'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/user-service/**'
      - 'modules/common/**'

jobs:
  deploy-user:
    name: Deploy User Service
    runs-on: ubuntu-latest
    
    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Test User Service
        run: ./gradlew :user:test

      - name: Build User Service
        run: ./gradlew :user:build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Latest Version from Docker Hub
        id: version
        shell: bash
        run: |
          set -e
          # Fetch all tags, keep only x.y.z, pick highest semver
          LATEST_TAG=$(curl -s "https://registry.hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/user-service/tags/?page_size=100" \
            | jq -r '.results[].name' \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -V | tail -1)
          if [[ -z "$LATEST_TAG" ]]; then
            NEW_VERSION="1.0.0"
          else
            IFS='.' read -r MAJOR MINOR PATCH <<< "$LATEST_TAG"
            PATCH=$((PATCH+1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          fi
          echo "latest_semver=${LATEST_TAG:-none}"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "New version: $NEW_VERSION"

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:${{ steps.version.outputs.new_version }} \
            -f services/user-service/Dockerfile .
          
          docker tag ${{ secrets.DOCKER_USERNAME }}/user-service:${{ steps.version.outputs.new_version }} \
            ${{ secrets.DOCKER_USERNAME }}/user-service:latest
          
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:${{ steps.version.outputs.new_version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest

      - name: Show Pushed Images
        run: |
          echo "Successfully pushed:"
          echo "🐳 ${{ secrets.DOCKER_USERNAME }}/user-service:${{ steps.version.outputs.new_version }}"
          echo "🐳 ${{ secrets.DOCKER_USERNAME }}/user-service:latest" 

      - name: Upload docker-compose.yml to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "docker-compose.yml"
          target: "/app"

      - name: SSH Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "📦 Deploying user-service version: ${{ steps.version.outputs.new_version }}"
            mkdir -p /app
            cd /app
            sed -i "s|image: ${{ secrets.DOCKER_USERNAME }}/user-service:.*|image: ${{ secrets.DOCKER_USERNAME }}/user-service:${{ steps.version.outputs.new_version }}|" docker-compose.yml
            docker compose -p streamix pull user-service
            docker compose -p streamix up -d --no-deps user-service