name: User Service Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'services/user-service/**'
      - 'modules/common/**'
      - 'dependencies.gradle'
      - 'build.gradle'
  pull_request:
    branches: [ main ]
    paths:
      - 'services/user-service/**'
      - 'modules/common/**'

jobs:
  test-user:
    runs-on: ubuntu-latest
    
    steps:
      - name: Download code
        uses: actions/checkout@v4
        
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Test User Service
        run: ./gradlew :user-service:test 